name: String Calculator
on: [push]
jobs:
  stringcalculator:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
       - name: List files in the repository
        run: 
          ls ${{ github.workspace }}
      - run: echo "The workflow is now ready to test your code on the runner."
      - uses: actions/setup-node@v2
        with:
            node-version: '12'
      - run: npm ci
      - run: npm run test